In [19]:
from glove_vec import read_glove_vectors
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
word_emb_dict = read_glove_vectors("/home/vasu/all_projects/CB/glove.6B.50d.txt")

## ODD ONE OUT USING Word2vec

In [23]:
apple = word_emb_dict["apple"].reshape(1,-1)
mango = word_emb_dict["mango"].reshape(1,-1)
banana = word_emb_dict["banana"].reshape(1,-1)
chair = word_emb_dict["chair"].reshape(1,-1)

In [35]:
avg_vec = np.sum(np.array([apple,mango,banana,chair]),axis=0)/4

In [37]:
cosine_similarity(apple,avg_vec)

array([[0.8258867]], dtype=float32)

In [38]:
cosine_similarity(mango,avg_vec)

array([[0.820125]], dtype=float32)

In [39]:
cosine_similarity(banana,avg_vec)

array([[0.8317692]], dtype=float32)

In [40]:
cosine_similarity(chair,avg_vec)

array([[0.47559774]], dtype=float32)