### NLTK

`Natural Language Processing Toolkit`

In [2]:
import nltk

## Lots of Applications
1) Translation
2) Sentiment Analysis
3) Topic Modelling
4) Document Classification/ Clustering
5) Generating new language eg Chatbots
6) Word Analgoies
7) Question Similarity Detection
8) Summarisation

In [16]:
from nltk.corpus import shakespeare,brown

In [17]:
len(brown.words())

1161192

In [12]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [19]:
data = brown.sents(categories=["humor","news"])

In [20]:
print(len(data))

5676


In [21]:
romance_data = brown.sents(categories=["romance"])
science_data = brown.sents(categories=["science_fiction"])

In [22]:
print(len(romance_data))

4431


In [23]:
print(len(science_data))


948


In [27]:
text = """This is Machine Learning class going on, 
        we are learning about algorithms!"""

text2 = """JEE Mains was conducted successfully! 
         10 lac candidates appeared, CBSE to decleare results online"""

review1 = "The movie was great, I liked it very much"
review2 = "The movie was okayish, acting was bad"

##### Convert Textual Data into Numerical Features
#### Steps
1. Tokenization -> Sentence & Word Level
2.





In [28]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [31]:
sents = sent_tokenize(text2)
print(sents)

['JEE Mains was conducted successfully!', '10 lac candidates appeared, CBSE to decleare results online']


In [40]:
print(sents[1])

10 lac candidates appeared, CBSE to decleare results online


In [44]:
words = word_tokenize(sents[1])
print(words)

['10', 'lac', 'candidates', 'appeared', ',', 'CBSE', 'to', 'decleare', 'results', 'online']


In [45]:
from nltk.corpus import stopwords

In [46]:
sw = set(stopwords.words('english'))

In [49]:
filtered_words = [w for w in words if w not in sw]

In [50]:
print(filtered_words)

['10', 'lac', 'candidates', 'appeared', ',', 'CBSE', 'decleare', 'results', 'online']


In [51]:
from nltk.tokenize import RegexpTokenizer

In [56]:
tokenizer = RegexpTokenizer('[a-zA-Z]+')
tokenizer.tokenize(sents[1])

['lac',
 'candidates',
 'appeared',
 'CBSE',
 'to',
 'decleare',
 'results',
 'online']

In [57]:
my_stopwords = ["a","an","the"]

In [58]:
text = """Boltz is running very fast, he is faster than others, 
            probably the fastest guy in the world"""

In [71]:
## Stemming
from nltk.stem import PorterStemmer,LancasterStemmer, SnowballStemmer


In [72]:
ps = PorterStemmer()
ls = LancasterStemmer()

In [73]:
ps.stem("fast")

'fast'

In [62]:
ps.stem("faster")

'faster'

In [63]:
ps.stem("fastest")

'fastest'

In [69]:
ps.stem("fasting")
ls.stem("fasting")

'fast'

In [65]:
ps.stem("crying")

'cri'

In [66]:
ps.stem("flying")

'fli'

In [70]:
ls.stem("flying")

'fly'

In [80]:
sb = SnowballStemmer(language='english')
sb.stem("greatest")

'greatest'

In [81]:
from nltk.stem import WordNetLemmatizer

In [82]:
wl = WordNetLemmatizer()

In [89]:
wl.lemmatize("greatest")

'greatest'

In [88]:
wl.lemmatize("loving",'v')

'love'

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
corpus = [
    text,
    text2,
    review1,
    review2
]

In [93]:
print(corpus)

['Boltz is running very fast, he is faster than others, \n            probably the fastest guy in the world', 'JEE Mains was conducted successfully! \n         10 lac candidates appeared, CBSE to decleare results online', 'The movie was great, I liked it very much', 'The movie was okayish, acting was bad']


In [119]:
cv = CountVectorizer(token_pattern='[A-Za-z]+',stop_words=sw,ngram_range=(1,2))
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [120]:
test_sentence = "Movie is good"
cv.transform([test_sentence]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [121]:
cv.get_feature_names()

['acting',
 'acting bad',
 'appeared',
 'appeared cbse',
 'bad',
 'boltz',
 'boltz running',
 'candidates',
 'candidates appeared',
 'cbse',
 'cbse decleare',
 'conducted',
 'conducted successfully',
 'decleare',
 'decleare results',
 'fast',
 'fast faster',
 'faster',
 'faster others',
 'fastest',
 'fastest guy',
 'great',
 'great liked',
 'guy',
 'guy world',
 'jee',
 'jee mains',
 'lac',
 'lac candidates',
 'liked',
 'liked much',
 'mains',
 'mains conducted',
 'movie',
 'movie great',
 'movie okayish',
 'much',
 'okayish',
 'okayish acting',
 'online',
 'others',
 'others probably',
 'probably',
 'probably fastest',
 'results',
 'results online',
 'running',
 'running fast',
 'successfully',
 'successfully lac',
 'world']

In [122]:
cv.vocabulary_

{'boltz': 5,
 'running': 46,
 'fast': 15,
 'faster': 17,
 'others': 40,
 'probably': 42,
 'fastest': 19,
 'guy': 23,
 'world': 50,
 'boltz running': 6,
 'running fast': 47,
 'fast faster': 16,
 'faster others': 18,
 'others probably': 41,
 'probably fastest': 43,
 'fastest guy': 20,
 'guy world': 24,
 'jee': 25,
 'mains': 31,
 'conducted': 11,
 'successfully': 48,
 'lac': 27,
 'candidates': 7,
 'appeared': 2,
 'cbse': 9,
 'decleare': 13,
 'results': 44,
 'online': 39,
 'jee mains': 26,
 'mains conducted': 32,
 'conducted successfully': 12,
 'successfully lac': 49,
 'lac candidates': 28,
 'candidates appeared': 8,
 'appeared cbse': 3,
 'cbse decleare': 10,
 'decleare results': 14,
 'results online': 45,
 'movie': 33,
 'great': 21,
 'liked': 29,
 'much': 36,
 'movie great': 34,
 'great liked': 22,
 'liked much': 30,
 'okayish': 37,
 'acting': 0,
 'bad': 4,
 'movie okayish': 35,
 'okayish acting': 38,
 'acting bad': 1}

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [112]:
tf = TfidfVectorizer()
tf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23407438,
        0.        , 0.        , 0.        , 0.        , 0.23407438,
        0.23407438, 0.23407438, 0.        , 0.23407438, 0.23407438,
        0.23407438, 0.46814876, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.23407438, 0.23407438, 0.        , 0.23407438,
        0.        , 0.23407438, 0.29881329, 0.        , 0.18454693,
        0.        , 0.23407438],
       [0.27310368, 0.        , 0.27310368, 0.        , 0.        ,
        0.27310368, 0.27310368, 0.27310368, 0.27310368, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.27310368, 0.27310368,
        0.        , 0.27310368, 0.        , 0.        , 0.        ,
        0.27310368, 0.        , 0.        , 0.27310368, 0.        ,
        0.27310368, 0.        , 0.        , 0.27310368, 0.        ,
        0.17431

In [118]:
tf.transform(["cbse movie isn't  good"]).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.78528828, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.6191303 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])